import type { ReportLanguage } from '../types/analysis';

export const normalizeReportLanguage = (value?: string | null): ReportLanguage => {
  const normalized = value?.trim().toLowerCase().replace('_', '-');
  if (normalized === 'en' || normalized?.startsWith('en-') || normalized === 'english') return 'en';
  if (normalized === 'ko' || normalized?.startsWith('ko-') || normalized === 'korean') return 'ko';
  return 'zh';
};

const REPORT_TEXT = {
  zh: {
    keyInsights: '核心洞察',
    noAnalysisSummary: '暂无分析结论',
    actionAdvice: '操作建议',
    noAdvice: '暂无建议',
    trendPrediction: '趋势预测',
    noPrediction: '暂无预测',
    marketSentiment: '市场情绪',
    strategyPoints: '策略点位',
    sniperLevels: '狙击点位',
    idealBuy: '理想买入',
    secondaryBuy: '二次买入',
    stopLoss: '止损价位',
    takeProfit: '止盈目标',
    noValue: '—',
    newsFeed: '资讯动态',
    relatedNews: '相关资讯',
    refresh: '刷新',
    retry: '重试',
    dismiss: '关闭',
    details: '查看详情',
    loadingNews: '加载资讯中...',
    noNews: '暂无相关资讯',
    noNewsDescription: '可稍后刷新以获取最新资讯。',
    openLink: '跳转',
    transparency: '透明度',
    traceability: '数据追溯',
    rawResult: '原始分析结果',
    analysisSnapshot: '分析快照',
    copy: '复制',
    copied: '已复制',
    recordId: '记录 ID',
    fullReport: '完整分析报告',
    loadingReport: '加载报告中...',
    loadReportFailed: '加载报告失败',
    copyMarkdownSource: '复制 Markdown 源码',
    copyPlainText: '复制纯文本',
    analysisModel: '分析模型',
    fearGreedIndex: '恐惧贪婪指数',
    boardLinkage: '板块联动',
    relatedBoards: '关联板块',
    leadingBoard: '领涨',
    laggingBoard: '领跌',
    neutralBoard: '中性',
    reanalyze: '重新分析',
  },
  en: {
    keyInsights: 'KEY INSIGHTS',
    noAnalysisSummary: 'No analysis summary yet',
    actionAdvice: 'Action Advice',
    noAdvice: 'No advice yet',
    trendPrediction: 'Trend Outlook',
    noPrediction: 'No forecast yet',
    marketSentiment: 'Market Sentiment',
    strategyPoints: 'STRATEGY POINTS',
    sniperLevels: 'Action Levels',
    idealBuy: 'Ideal Entry',
    secondaryBuy: 'Secondary Entry',
    stopLoss: 'Stop Loss',
    takeProfit: 'Take Profit',
    noValue: '—',
    newsFeed: 'NEWS FEED',
    relatedNews: 'Related News',
    refresh: 'Refresh',
    retry: 'Retry',
    dismiss: 'Close',
    details: 'View details',
    loadingNews: 'Loading news...',
    noNews: 'No related news',
    noNewsDescription: 'Refresh later to check for the latest updates.',
    openLink: 'Open',
    transparency: 'TRANSPARENCY',
    traceability: 'Data Traceability',
    rawResult: 'Raw Analysis Result',
    analysisSnapshot: 'Analysis Snapshot',
    copy: 'Copy',
    copied: 'Copied!',
    recordId: 'Record ID',
    fullReport: 'Full Analysis Report',
    loadingReport: 'Loading report...',
    loadReportFailed: 'Failed to load report',
    copyMarkdownSource: 'Copy Markdown Source',
    copyPlainText: 'Copy Plain Text',
    analysisModel: 'Model',
    fearGreedIndex: 'Fear & Greed Index',
    boardLinkage: 'BOARD LINKAGE',
    relatedBoards: 'Related Boards',
    leadingBoard: 'Leading',
    laggingBoard: 'Lagging',
    neutralBoard: 'Neutral',
    reanalyze: 'Reanalyze',
  },
  ko: {
    keyInsights: '핵심 인사이트',
    noAnalysisSummary: '분석 요약이 없습니다',
    actionAdvice: '매매 의견',
    noAdvice: '의견이 없습니다',
    trendPrediction: '추세 전망',
    noPrediction: '전망이 없습니다',
    marketSentiment: '시장 심리',
    strategyPoints: '전략 가격대',
    sniperLevels: '매매 가격대',
    idealBuy: '1차 매수',
    secondaryBuy: '2차 매수',
    stopLoss: '손절가',
    takeProfit: '목표가',
    noValue: '—',
    newsFeed: '뉴스 피드',
    relatedNews: '관련 뉴스',
    refresh: '새로고침',
    retry: '다시 시도',
    dismiss: '닫기',
    details: '상세 보기',
    loadingNews: '뉴스를 불러오는 중...',
    noNews: '관련 뉴스가 없습니다',
    noNewsDescription: '잠시 후 새로고침하여 최신 소식을 확인하세요.',
    openLink: '열기',
    transparency: '투명성',
    traceability: '데이터 추적',
    rawResult: '원본 분석 결과',
    analysisSnapshot: '분석 스냅샷',
    copy: '복사',
    copied: '복사됨!',
    recordId: '기록 ID',
    fullReport: '전체 분석 보고서',
    loadingReport: '보고서를 불러오는 중...',
    loadReportFailed: '보고서를 불러오지 못했습니다',
    copyMarkdownSource: 'Markdown 원문 복사',
    copyPlainText: '일반 텍스트 복사',
    analysisModel: '분석 모델',
    fearGreedIndex: '공포·탐욕 지수',
    boardLinkage: '업종 연계',
    relatedBoards: '관련 업종',
    leadingBoard: '상승 주도',
    laggingBoard: '하락 주도',
    neutralBoard: '중립',
    reanalyze: '다시 분석',
  },
} as const;

export const getReportText = (language?: string | null) => REPORT_TEXT[normalizeReportLanguage(language)];
