import type { BacktestPhaseFilter } from '../types/backtest';
import type { AlertTargetScope, AlertType, MarketLightStatus, MarketRegion, PortfolioStopLossMode } from '../types/alerts';
import type { PortfolioCashDirection, PortfolioCorporateActionType, PortfolioSide } from '../types/portfolio';
import type { UiLanguage } from '../i18n/uiText';

type Option<T extends string = string> = { value: T; label: string };
const alertTypes: AlertType[] = ['price_cross', 'price_change_percent', 'volume_spike', 'ma_price_cross', 'rsi_threshold', 'macd_cross', 'kdj_cross', 'cci_threshold', 'portfolio_stop_loss', 'portfolio_concentration', 'portfolio_drawdown', 'portfolio_price_stale', 'market_light_status', 'market_light_score_drop'];
const symbolAlertTypes = alertTypes.slice(0, 8);
const portfolioAlertTypes = alertTypes.slice(8, 12);
const marketAlertTypes = alertTypes.slice(12);

export const BACKTEST_TEXT = {
  zh: { documentTitle: '策略回测 - DSA', codePlaceholder: '按股票代码筛选（留空表示全部）', filter: '筛选', evalWindow: '评估窗口', phase: '阶段', startDate: '开始日期', startDateAria: '分析开始日期', endDate: '结束日期', endDateAria: '分析结束日期', oneDayValidation: '1 日验证', forceRerun: '强制重跑', running: '回测中...', runBacktest: '运行回测', oneDayModeDescription: '1 日验证模式会用下一个交易日收盘表现校验 AI 预测。', windowModeDescription: '将评估窗口设为 1，可查看 AI 预测与下一个交易日收盘表现的匹配情况。', overallPerformance: '整体表现', noMetricsTitle: '暂无指标', noMetricsDescription: '运行回测后会生成组合级表现指标。', loadingResults: '正在加载结果...', noResultsTitle: '暂无结果', noResultsDescription: '运行回测后可评估历史分析准确性。', nextDayValidation: '次日验证', resultSet: '结果集', allStocks: '全部股票', filteredStock: '筛选 {code}', dayWindow: '{days} 日窗口', fromDate: '自 {date}', toDate: '至 {date}', scrollHint: '小屏幕可横向滚动', stock: '股票', analysisDate: '分析日期', aiPrediction: 'AI 预测', actualPerformance: '实际表现', windowReturn: '窗口收益', accuracy: '准确性', directionMatch: '方向匹配', result: '结果', status: '状态', totalPage: '共 {total} 条结果 · 第 {page} / {pages} 页', directionAccuracy: '方向准确率', winRate: '胜率', avgSimulatedReturn: '平均模拟收益', avgStockReturn: '平均个股收益', stopLossTriggerRate: '止损触发率', takeProfitTriggerRate: '止盈触发率', avgDaysToFirstHit: '平均命中天数', evaluationCount: '评估数', outcomeSummary: '盈 / 亏 / 中', phaseDistribution: '阶段分布：{text}', processed: '已处理:', saved: '已保存:', completed: '已完成:', insufficient: '数据不足:', errors: '错误:', yes: '是', no: '否', unknown: '未知' },
  en: { documentTitle: 'Strategy Backtest - DSA', codePlaceholder: 'Filter by stock code (leave empty for all)', filter: 'Filter', evalWindow: 'Evaluation window', phase: 'Phase', startDate: 'Start date', startDateAria: 'Analysis start date', endDate: 'End date', endDateAria: 'Analysis end date', oneDayValidation: '1D validation', forceRerun: 'Force rerun', running: 'Backtesting...', runBacktest: 'Run backtest', oneDayModeDescription: '1D validation checks AI predictions against the next trading day close.', windowModeDescription: 'Set the evaluation window to 1 to compare AI predictions with the next trading day close.', overallPerformance: 'Overall performance', noMetricsTitle: 'No metrics', noMetricsDescription: 'Portfolio-level performance metrics appear after a backtest runs.', loadingResults: 'Loading results...', noResultsTitle: 'No results', noResultsDescription: 'Run a backtest to evaluate historical analysis accuracy.', nextDayValidation: 'Next-day validation', resultSet: 'Result set', allStocks: 'All stocks', filteredStock: 'Filtered {code}', dayWindow: '{days}-day window', fromDate: 'from {date}', toDate: 'to {date}', scrollHint: 'Scroll horizontally on small screens', stock: 'Stock', analysisDate: 'Analysis date', aiPrediction: 'AI prediction', actualPerformance: 'Actual performance', windowReturn: 'Window return', accuracy: 'Accuracy', directionMatch: 'Direction match', result: 'Result', status: 'Status', totalPage: '{total} results · Page {page} / {pages}', directionAccuracy: 'Direction accuracy', winRate: 'Win rate', avgSimulatedReturn: 'Avg simulated return', avgStockReturn: 'Avg stock return', stopLossTriggerRate: 'Stop-loss trigger rate', takeProfitTriggerRate: 'Take-profit trigger rate', avgDaysToFirstHit: 'Avg days to first hit', evaluationCount: 'Evaluations', outcomeSummary: 'Win / Loss / Neutral', phaseDistribution: 'Phase breakdown: {text}', processed: 'Processed:', saved: 'Saved:', completed: 'Completed:', insufficient: 'Insufficient:', errors: 'Errors:', yes: 'Yes', no: 'No', unknown: 'Unknown' },
  ko: { documentTitle: '전략 백테스트 - DSA', codePlaceholder: '종목 코드로 필터 (비워 두면 전체)', filter: '필터', evalWindow: '평가 기간', phase: '장 구분', startDate: '시작일', startDateAria: '분석 시작일', endDate: '종료일', endDateAria: '분석 종료일', oneDayValidation: '1일 검증', forceRerun: '강제 재실행', running: '백테스트 중...', runBacktest: '백테스트 실행', oneDayModeDescription: '1일 검증은 AI 예측을 다음 거래일 종가와 비교합니다.', windowModeDescription: '평가 기간을 1로 설정하면 AI 예측과 다음 거래일 종가를 비교할 수 있습니다.', overallPerformance: '전체 성과', noMetricsTitle: '지표 없음', noMetricsDescription: '백테스트를 실행하면 포트폴리오 성과 지표가 표시됩니다.', loadingResults: '결과를 불러오는 중...', noResultsTitle: '결과 없음', noResultsDescription: '백테스트를 실행해 과거 분석 정확도를 평가하세요.', nextDayValidation: '다음 날 검증', resultSet: '결과 목록', allStocks: '전체 종목', filteredStock: '{code} 필터', dayWindow: '{days}일 구간', fromDate: '{date}부터', toDate: '{date}까지', scrollHint: '작은 화면에서는 가로로 스크롤하세요', stock: '종목', analysisDate: '분석일', aiPrediction: 'AI 예측', actualPerformance: '실제 성과', windowReturn: '구간 수익률', accuracy: '정확도', directionMatch: '방향 일치', result: '결과', status: '상태', totalPage: '총 {total}건 · {page} / {pages}페이지', directionAccuracy: '방향 정확도', winRate: '승률', avgSimulatedReturn: '평균 모의 수익률', avgStockReturn: '평균 종목 수익률', stopLossTriggerRate: '손절 발동률', takeProfitTriggerRate: '익절 발동률', avgDaysToFirstHit: '첫 도달 평균 일수', evaluationCount: '평가 건수', outcomeSummary: '승 / 패 / 중립', phaseDistribution: '장 구분: {text}', processed: '처리:', saved: '저장:', completed: '완료:', insufficient: '데이터 부족:', errors: '오류:', yes: '예', no: '아니요', unknown: '알 수 없음' },
} as const;

export const BACKTEST_PHASE_FILTER_OPTIONS: Record<UiLanguage, Array<Option<BacktestPhaseFilter>>> = {
  zh: [{ value: 'all', label: '全部阶段' }, { value: 'premarket', label: '盘前' }, { value: 'intraday', label: '盘中' }, { value: 'postmarket', label: '盘后' }, { value: 'unknown', label: '未知' }],
  en: [{ value: 'all', label: 'All phases' }, { value: 'premarket', label: 'Pre-market' }, { value: 'intraday', label: 'Intraday' }, { value: 'postmarket', label: 'Post-market' }, { value: 'unknown', label: 'Unknown' }],
  ko: [{ value: 'all', label: '전체 구간' }, { value: 'premarket', label: '장전' }, { value: 'intraday', label: '장중' }, { value: 'postmarket', label: '장후' }, { value: 'unknown', label: '알 수 없음' }],
};
export const BACKTEST_PHASE_LABELS: Record<UiLanguage, Record<string, string>> = { zh: { premarket: '盘前', intraday: '盘中', postmarket: '盘后', unknown: '未知' }, en: { premarket: 'Pre-market', intraday: 'Intraday', postmarket: 'Post-market', unknown: 'Unknown' }, ko: { premarket: '장전', intraday: '장중', postmarket: '장후', unknown: '알 수 없음' } };
export const BACKTEST_OUTCOME_LABELS: Record<UiLanguage, Record<string, string>> = { zh: { win: '盈利', loss: '亏损', neutral: '中性' }, en: { win: 'Win', loss: 'Loss', neutral: 'Neutral' }, ko: { win: '수익', loss: '손실', neutral: '중립' } };
export const BACKTEST_STATUS_LABELS: Record<UiLanguage, Record<string, string>> = { zh: { completed: '已完成', insufficient: '数据不足', insufficient_data: '数据不足', error: '错误' }, en: { completed: 'Completed', insufficient: 'Insufficient data', insufficient_data: 'Insufficient data', error: 'Error' }, ko: { completed: '완료', insufficient: '데이터 부족', insufficient_data: '데이터 부족', error: '오류' } };
export const BACKTEST_MOVEMENT_LABELS: Record<UiLanguage, Record<string, string>> = { zh: { up: '上涨', down: '下跌', flat: '持平' }, en: { up: 'Up', down: 'Down', flat: 'Flat' }, ko: { up: '상승', down: '하락', flat: '보합' } };
export const BACKTEST_DIRECTION_EXPECTED_LABELS: Record<UiLanguage, Record<string, string>> = { zh: { long: '做多', cash: '空仓', up: '看涨', down: '看跌', not_down: '不看跌', flat: '持平' }, en: { long: 'Long', cash: 'Cash', up: 'Bullish', down: 'Bearish', not_down: 'Not bearish', flat: 'Flat' }, ko: { long: '매수', cash: '현금', up: '상승', down: '하락', not_down: '비하락', flat: '보합' } };

export const ALERT_TYPE_LABELS: Record<UiLanguage, Record<AlertType, string>> = {
  zh: { price_cross: '价格突破', price_change_percent: '涨跌幅', volume_spike: '成交量放大', ma_price_cross: '价格均线穿越', rsi_threshold: 'RSI 阈值', macd_cross: 'MACD 金叉/死叉', kdj_cross: 'KDJ 金叉/死叉', cci_threshold: 'CCI 阈值', portfolio_stop_loss: '组合止损', portfolio_concentration: '组合集中度', portfolio_drawdown: '组合回撤', portfolio_price_stale: '组合价格状态', market_light_status: '大盘红绿灯状态', market_light_score_drop: '大盘红绿灯分数下降' },
  en: { price_cross: 'Price crossing', price_change_percent: 'Price change', volume_spike: 'Volume spike', ma_price_cross: 'Price/MA crossing', rsi_threshold: 'RSI threshold', macd_cross: 'MACD cross', kdj_cross: 'KDJ cross', cci_threshold: 'CCI threshold', portfolio_stop_loss: 'Portfolio stop loss', portfolio_concentration: 'Portfolio concentration', portfolio_drawdown: 'Portfolio drawdown', portfolio_price_stale: 'Portfolio price status', market_light_status: 'Market traffic light status', market_light_score_drop: 'Market traffic light score drop' },
  ko: { price_cross: '가격 돌파', price_change_percent: '등락률', volume_spike: '거래량 급증', ma_price_cross: '가격/이동평균선 교차', rsi_threshold: 'RSI 기준값', macd_cross: 'MACD 교차', kdj_cross: 'KDJ 교차', cci_threshold: 'CCI 기준값', portfolio_stop_loss: '포트폴리오 손절', portfolio_concentration: '포트폴리오 집중도', portfolio_drawdown: '포트폴리오 낙폭', portfolio_price_stale: '포트폴리오 가격 상태', market_light_status: '시장 신호등 상태', market_light_score_drop: '시장 신호등 점수 하락' },
};
export const ALERT_SEVERITY_LABELS: Record<UiLanguage, Record<string, string>> = { zh: { info: '提示', warning: '警告', critical: '严重' }, en: { info: 'Info', warning: 'Warning', critical: 'Critical' }, ko: { info: '안내', warning: '경고', critical: '심각' } };
export const ALERT_SCOPE_LABELS: Record<UiLanguage, Record<AlertTargetScope, string>> = { zh: { single_symbol: '单标的', watchlist: '自选股', portfolio_holdings: '持仓标的', portfolio_account: '持仓账户', market: '大盘市场' }, en: { single_symbol: 'Single symbol', watchlist: 'Watchlist', portfolio_holdings: 'Portfolio holdings', portfolio_account: 'Portfolio account', market: 'Market' }, ko: { single_symbol: '개별 종목', watchlist: '관심 종목', portfolio_holdings: '보유 종목', portfolio_account: '포트폴리오 계좌', market: '시장' } };
export const ALERT_MARKET_REGION_LABELS: Record<UiLanguage, Record<MarketRegion, string>> = { zh: { cn: 'A 股', hk: '港股', us: '美股', jp: '日股', kr: '韩股' }, en: { cn: 'A-shares', hk: 'Hong Kong', us: 'US', jp: 'Japan', kr: 'Korea' }, ko: { cn: '중국 A주', hk: '홍콩', us: '미국', jp: '일본', kr: '한국' } };
export const ALERT_MARKET_LIGHT_STATUS_LABELS: Record<UiLanguage, Record<MarketLightStatus, string>> = { zh: { yellow: '黄灯', red: '红灯' }, en: { yellow: 'Yellow', red: 'Red' }, ko: { yellow: '노란불', red: '빨간불' } };
export const ALERT_DIRECTION_LABELS = {
  zh: { abovePrice: '上破', belowPrice: '下破', upChange: '上涨', downChange: '下跌', aboveThreshold: '上穿', belowThreshold: '下穿', bullishCross: '金叉', bearishCross: '死叉', stopLossNear: '接近止损', stopLossBreach: '已触发止损' },
  en: { abovePrice: 'above', belowPrice: 'below', upChange: 'up', downChange: 'down', aboveThreshold: 'above', belowThreshold: 'below', bullishCross: 'bullish cross', bearishCross: 'bearish cross', stopLossNear: 'Near stop loss', stopLossBreach: 'Stop loss breached' },
  ko: { abovePrice: '상향 돌파', belowPrice: '하향 돌파', upChange: '상승', downChange: '하락', aboveThreshold: '상향 돌파', belowThreshold: '하향 돌파', bullishCross: '골든크로스', bearishCross: '데드크로스', stopLossNear: '손절가 근접', stopLossBreach: '손절가 도달' },
} as const;
export const ALERT_LIST_TEXT = {
  zh: { title: '告警规则', subtitle: '{total} 条规则', enabledFilter: '启停状态', alertTypeFilter: '规则类型', loadingRules: '正在加载规则', emptyTitle: '暂无告警规则', emptyDescription: '创建规则后，后台评估任务会按轮询周期处理已启用的告警。', rule: '规则', target: '目标', type: '类型', parameters: '参数', status: '状态', cooldown: '冷却', updatedAt: '更新时间', action: '操作', source: '来源：{source}', allAccounts: '全部账户', accountTarget: '账户 {target}', enabled: '已启用', disabled: '已停用', coolingDown: '冷却中', notCoolingDown: '未冷却', childTargetCooldown: '子目标见触发历史', test: '测试', testing: '测试中', disabling: '停用中', enabling: '启用中', disable: '停用', enable: '启用', delete: '删除', cancel: '取消', scoreDropAtLeast: 'Score 下降 >= {value}', deleteAria: '删除 {name}', deleteTitle: '删除告警规则', deleteMessage: '确认删除「{name}」吗？该操作不会删除已有触发历史。' },
  en: { title: 'Alert rules', subtitle: '{total} rules', enabledFilter: 'Status', alertTypeFilter: 'Rule type', loadingRules: 'Loading rules', emptyTitle: 'No alert rules', emptyDescription: 'After rules are created, background evaluation processes enabled alerts on the polling schedule.', rule: 'Rule', target: 'Target', type: 'Type', parameters: 'Parameters', status: 'Status', cooldown: 'Cooldown', updatedAt: 'Updated', action: 'Actions', source: 'Source: {source}', allAccounts: 'All accounts', accountTarget: 'Account {target}', enabled: 'Enabled', disabled: 'Disabled', coolingDown: 'Cooling down', notCoolingDown: 'Not cooling down', childTargetCooldown: 'Per-target cooldowns are in trigger history', test: 'Test', testing: 'Testing', disabling: 'Disabling', enabling: 'Enabling', disable: 'Disable', enable: 'Enable', delete: 'Delete', cancel: 'Cancel', scoreDropAtLeast: 'Score drop >= {value}', deleteAria: 'Delete {name}', deleteTitle: 'Delete alert rule', deleteMessage: 'Delete "{name}"? Existing trigger history will be kept.' },
  ko: { title: '알림 규칙', subtitle: '총 {total}개', enabledFilter: '상태', alertTypeFilter: '규칙 유형', loadingRules: '규칙을 불러오는 중', emptyTitle: '알림 규칙 없음', emptyDescription: '규칙을 만들면 백그라운드 평가 작업이 활성화된 알림을 주기적으로 처리합니다.', rule: '규칙', target: '대상', type: '유형', parameters: '조건', status: '상태', cooldown: '재알림 대기', updatedAt: '수정 시각', action: '작업', source: '출처: {source}', allAccounts: '전체 계좌', accountTarget: '계좌 {target}', enabled: '활성', disabled: '비활성', coolingDown: '재알림 대기 중', notCoolingDown: '대기 없음', childTargetCooldown: '대상별 대기 상태는 발동 기록에서 확인', test: '테스트', testing: '테스트 중', disabling: '비활성화 중', enabling: '활성화 중', disable: '비활성화', enable: '활성화', delete: '삭제', cancel: '취소', scoreDropAtLeast: '점수 하락 >= {value}', deleteAria: '{name} 삭제', deleteTitle: '알림 규칙 삭제', deleteMessage: '"{name}" 규칙을 삭제할까요? 기존 발동 기록은 유지됩니다.' },
} as const;
export const ALERT_ENABLED_FILTER_OPTIONS: Record<UiLanguage, Array<Option<'all' | 'enabled' | 'disabled'>>> = { zh: [{ value: 'all', label: '全部状态' }, { value: 'enabled', label: '已启用' }, { value: 'disabled', label: '已停用' }], en: [{ value: 'all', label: 'All statuses' }, { value: 'enabled', label: 'Enabled' }, { value: 'disabled', label: 'Disabled' }], ko: [{ value: 'all', label: '전체 상태' }, { value: 'enabled', label: '활성' }, { value: 'disabled', label: '비활성' }] };
export const ALERT_TYPE_FILTER_OPTIONS: Record<UiLanguage, Array<Option<'all' | AlertType>>> = { zh: [{ value: 'all', label: '全部类型' }, ...alertTypes.map((value) => ({ value, label: ALERT_TYPE_LABELS.zh[value] }))], en: [{ value: 'all', label: 'All types' }, ...alertTypes.map((value) => ({ value, label: ALERT_TYPE_LABELS.en[value] }))], ko: [{ value: 'all', label: '전체 유형' }, ...alertTypes.map((value) => ({ value, label: ALERT_TYPE_LABELS.ko[value] }))] };
export const ALERT_FORM_TEXT = {
  zh: { accountLoadFailed: '账户加载失败', allAccounts: '全部账户', cardTitle: '创建告警规则', cardSubtitle: 'Web 告警中心', ruleName: '规则名称', ruleNamePlaceholder: '可选，例如 茅台价格突破', targetScope: '目标范围', targetCode: '标的代码', target: '目标', marketRegion: '市场区域', account: '账户', ruleType: '规则类型', severity: '严重级别', direction: '方向', priceThreshold: '价格阈值', changePctThreshold: '涨跌幅阈值（%）', volumeMultiplier: '成交量放大倍数', crossDirection: '交叉方向', thresholdDirection: '阈值方向', maDirection: '穿越方向', maWindow: '均线周期', rsiPeriod: 'RSI 周期', rsiThreshold: 'RSI 阈值', fastPeriod: '快线周期', slowPeriod: '慢线周期', signalPeriod: '信号周期', kdjPeriod: 'KDJ 周期', kPeriod: 'K 平滑周期', dPeriod: 'D 平滑周期', cciPeriod: 'CCI 周期', cciThreshold: 'CCI 阈值', stopLossMode: '止损模式', triggerStatus: '触发状态', scoreDropThreshold: 'Score 下降阈值', enableAfterCreate: '创建后立即启用', creating: '创建中...', create: '创建规则', positiveNumber: '{label}必须是大于 0 的数字', integerRange: '{label}必须是 {min} 到 {max} 的整数', required: '{label}不能为空', finiteNumber: '{label}必须是有效数字', rsiRange: 'RSI 阈值必须在 0 到 100 之间', requiredBarsLimit: '{label} 周期组合需要 {requiredBars} 根日线，最多支持 {max} 根', fastLessThanSlow: '快线周期必须小于慢线周期', noMarketStatus: '至少选择一个红绿灯状态', invalidStockCode: '股票代码格式不正确' },
  en: { accountLoadFailed: 'Account loading failed', allAccounts: 'All accounts', cardTitle: 'Create alert rule', cardSubtitle: 'Web alert center', ruleName: 'Rule name', ruleNamePlaceholder: 'Optional, e.g. Moutai price crossing', targetScope: 'Target scope', targetCode: 'Symbol', target: 'Target', marketRegion: 'Market region', account: 'Account', ruleType: 'Rule type', severity: 'Severity', direction: 'Direction', priceThreshold: 'Price threshold', changePctThreshold: 'Change threshold (%)', volumeMultiplier: 'Volume multiplier', crossDirection: 'Cross direction', thresholdDirection: 'Threshold direction', maDirection: 'Cross direction', maWindow: 'MA window', rsiPeriod: 'RSI period', rsiThreshold: 'RSI threshold', fastPeriod: 'Fast period', slowPeriod: 'Slow period', signalPeriod: 'Signal period', kdjPeriod: 'KDJ period', kPeriod: 'K smoothing period', dPeriod: 'D smoothing period', cciPeriod: 'CCI period', cciThreshold: 'CCI threshold', stopLossMode: 'Stop-loss mode', triggerStatus: 'Trigger status', scoreDropThreshold: 'Score drop threshold', enableAfterCreate: 'Enable immediately', creating: 'Creating...', create: 'Create rule', positiveNumber: '{label} must be a number greater than 0', integerRange: '{label} must be an integer from {min} to {max}', required: '{label} is required', finiteNumber: '{label} must be a valid number', rsiRange: 'RSI threshold must be between 0 and 100', requiredBarsLimit: '{label} requires {requiredBars} daily bars, up to {max} are supported', fastLessThanSlow: 'Fast period must be less than slow period', noMarketStatus: 'Select at least one traffic light status', invalidStockCode: 'Invalid stock code format' },
  ko: { accountLoadFailed: '계좌를 불러오지 못했습니다', allAccounts: '전체 계좌', cardTitle: '알림 규칙 만들기', cardSubtitle: '웹 알림 센터', ruleName: '규칙 이름', ruleNamePlaceholder: '선택 사항 (예: 삼성전자 가격 돌파)', targetScope: '대상 범위', targetCode: '종목 코드', target: '대상', marketRegion: '시장', account: '계좌', ruleType: '규칙 유형', severity: '심각도', direction: '방향', priceThreshold: '가격 기준값', changePctThreshold: '등락률 기준값 (%)', volumeMultiplier: '거래량 배수', crossDirection: '교차 방향', thresholdDirection: '기준값 방향', maDirection: '교차 방향', maWindow: '이동평균 기간', rsiPeriod: 'RSI 기간', rsiThreshold: 'RSI 기준값', fastPeriod: '단기 기간', slowPeriod: '장기 기간', signalPeriod: '시그널 기간', kdjPeriod: 'KDJ 기간', kPeriod: 'K 완화 기간', dPeriod: 'D 완화 기간', cciPeriod: 'CCI 기간', cciThreshold: 'CCI 기준값', stopLossMode: '손절 방식', triggerStatus: '발동 상태', scoreDropThreshold: '점수 하락 기준값', enableAfterCreate: '생성 즉시 활성화', creating: '생성 중...', create: '규칙 만들기', positiveNumber: '{label}은(는) 0보다 큰 숫자여야 합니다', integerRange: '{label}은(는) {min}~{max}의 정수여야 합니다', required: '{label}은(는) 필수입니다', finiteNumber: '{label}은(는) 올바른 숫자여야 합니다', rsiRange: 'RSI 기준값은 0~100이어야 합니다', requiredBarsLimit: '{label} 기간 조합에는 일봉 {requiredBars}개가 필요하며 최대 {max}개까지 지원합니다', fastLessThanSlow: '단기 기간은 장기 기간보다 작아야 합니다', noMarketStatus: '시장 신호등 상태를 하나 이상 선택하세요', invalidStockCode: '종목 코드 형식이 올바르지 않습니다' },
} as const;
export const ALERT_SYMBOL_TYPE_OPTIONS: Record<UiLanguage, Array<Option<AlertType>>> = { zh: symbolAlertTypes.map((value) => ({ value, label: ALERT_TYPE_LABELS.zh[value] })), en: symbolAlertTypes.map((value) => ({ value, label: ALERT_TYPE_LABELS.en[value] })), ko: symbolAlertTypes.map((value) => ({ value, label: ALERT_TYPE_LABELS.ko[value] })) };
export const ALERT_PORTFOLIO_TYPE_OPTIONS: Record<UiLanguage, Array<Option<AlertType>>> = { zh: portfolioAlertTypes.map((value) => ({ value, label: ALERT_TYPE_LABELS.zh[value] })), en: portfolioAlertTypes.map((value) => ({ value, label: ALERT_TYPE_LABELS.en[value] })), ko: portfolioAlertTypes.map((value) => ({ value, label: ALERT_TYPE_LABELS.ko[value] })) };
export const ALERT_MARKET_TYPE_OPTIONS: Record<UiLanguage, Array<Option<AlertType>>> = { zh: marketAlertTypes.map((value) => ({ value, label: ALERT_TYPE_LABELS.zh[value] })), en: marketAlertTypes.map((value) => ({ value, label: ALERT_TYPE_LABELS.en[value] })), ko: marketAlertTypes.map((value) => ({ value, label: ALERT_TYPE_LABELS.ko[value] })) };
export const ALERT_TARGET_SCOPE_OPTIONS: Record<UiLanguage, Array<Option<AlertTargetScope>>> = { zh: Object.entries(ALERT_SCOPE_LABELS.zh).map(([value, label]) => ({ value: value as AlertTargetScope, label })), en: Object.entries(ALERT_SCOPE_LABELS.en).map(([value, label]) => ({ value: value as AlertTargetScope, label })), ko: Object.entries(ALERT_SCOPE_LABELS.ko).map(([value, label]) => ({ value: value as AlertTargetScope, label })) };
export const ALERT_SEVERITY_OPTIONS: Record<UiLanguage, Array<Option<'info' | 'warning' | 'critical'>>> = { zh: Object.entries(ALERT_SEVERITY_LABELS.zh).map(([value, label]) => ({ value: value as 'info' | 'warning' | 'critical', label })), en: Object.entries(ALERT_SEVERITY_LABELS.en).map(([value, label]) => ({ value: value as 'info' | 'warning' | 'critical', label })), ko: Object.entries(ALERT_SEVERITY_LABELS.ko).map(([value, label]) => ({ value: value as 'info' | 'warning' | 'critical', label })) };
export const ALERT_PRICE_DIRECTION_OPTIONS: Record<UiLanguage, Array<Option<'above' | 'below'>>> = { zh: [{ value: 'above', label: '上破' }, { value: 'below', label: '下破' }], en: [{ value: 'above', label: 'Crosses above' }, { value: 'below', label: 'Crosses below' }], ko: [{ value: 'above', label: '상향 돌파' }, { value: 'below', label: '하향 돌파' }] };
export const ALERT_CHANGE_DIRECTION_OPTIONS: Record<UiLanguage, Array<Option<'up' | 'down'>>> = { zh: [{ value: 'up', label: '上涨达到' }, { value: 'down', label: '下跌达到' }], en: [{ value: 'up', label: 'Rises by' }, { value: 'down', label: 'Falls by' }], ko: [{ value: 'up', label: '상승 도달' }, { value: 'down', label: '하락 도달' }] };
export const ALERT_THRESHOLD_DIRECTION_OPTIONS: Record<UiLanguage, Array<Option<'above' | 'below'>>> = { zh: [{ value: 'above', label: '上穿' }, { value: 'below', label: '下穿' }], en: [{ value: 'above', label: 'Crosses above' }, { value: 'below', label: 'Crosses below' }], ko: [{ value: 'above', label: '상향 돌파' }, { value: 'below', label: '하향 돌파' }] };
export const ALERT_CROSS_DIRECTION_OPTIONS: Record<UiLanguage, Array<Option<'bullish_cross' | 'bearish_cross'>>> = { zh: [{ value: 'bullish_cross', label: '金叉' }, { value: 'bearish_cross', label: '死叉' }], en: [{ value: 'bullish_cross', label: 'Bullish cross' }, { value: 'bearish_cross', label: 'Bearish cross' }], ko: [{ value: 'bullish_cross', label: '골든크로스' }, { value: 'bearish_cross', label: '데드크로스' }] };
export const ALERT_STOP_LOSS_MODE_OPTIONS: Record<UiLanguage, Array<Option<PortfolioStopLossMode>>> = { zh: [{ value: 'near', label: '接近止损' }, { value: 'breach', label: '已触发止损' }], en: [{ value: 'near', label: 'Near stop loss' }, { value: 'breach', label: 'Stop loss breached' }], ko: [{ value: 'near', label: '손절가 근접' }, { value: 'breach', label: '손절가 도달' }] };
export const ALERT_MARKET_REGION_OPTIONS: Record<UiLanguage, Array<Option<MarketRegion>>> = { zh: [{ value: 'cn', label: 'A 股（cn）' }, { value: 'hk', label: '港股（hk）' }, { value: 'us', label: '美股（us）' }, { value: 'jp', label: '日股（jp）' }, { value: 'kr', label: '韩股（kr）' }], en: [{ value: 'cn', label: 'A-shares (cn)' }, { value: 'hk', label: 'Hong Kong (hk)' }, { value: 'us', label: 'US (us)' }, { value: 'jp', label: 'Japan (jp)' }, { value: 'kr', label: 'Korea (kr)' }], ko: [{ value: 'cn', label: '중국 A주 (cn)' }, { value: 'hk', label: '홍콩 (hk)' }, { value: 'us', label: '미국 (us)' }, { value: 'jp', label: '일본 (jp)' }, { value: 'kr', label: '한국 (kr)' }] };
export const ALERT_MARKET_LIGHT_STATUS_OPTIONS: Record<UiLanguage, Array<Option<MarketLightStatus>>> = { zh: [{ value: 'red', label: '红灯' }, { value: 'yellow', label: '黄灯' }], en: [{ value: 'red', label: 'Red' }, { value: 'yellow', label: 'Yellow' }], ko: [{ value: 'red', label: '빨간불' }, { value: 'yellow', label: '노란불' }] };

export const PORTFOLIO_TEXT = {
  zh: { documentTitle: '持仓分析 - DSA', title: '持仓管理', description: '组合快照、手工录入、CSV 导入与风险分析（支持全组合 / 单账户切换）', accountView: '账户视图', allAccounts: '全部账户', costMethod: '成本口径', fifo: '先进先出（FIFO）', avg: '均价成本（AVG）', collapseCreate: '收起新建', createAccount: '新建账户', deleteAccount: '删除账户', deletingAccount: '删除中...', deleteAccountTitle: '删除持仓账户', deleteAccountConfirm: '确认删除', deleteAccountMessage: '确认删除账户 {name}（#{id}）吗？删除后该账户会从默认列表、快照、风险和录入入口隐藏；历史流水不会物理删除。', refreshing: '刷新中...', refreshData: '刷新数据', noAccounts: '还没有可用账户，请先创建账户后再录入交易或导入 CSV。', riskDegraded: '风险模块降级', operationHint: '操作提示', analysisTask: '分析任务', totalEquity: '总权益', totalMarketValue: '总市值', totalCash: '总现金', fxStatus: '汇率状态', refreshFx: '刷新汇率', stale: '过期', latest: '最新', fxRefreshResult: '汇率刷新结果', positionsTitle: '持仓明细', countItems: '共 {count} 项', noPositionsTitle: '当前无持仓数据', noPositionsDescription: '录入交易或导入 CSV 后，这里会展示按账户汇总的持仓明细。', account: '账户', code: '代码', quantity: '数量', avgCost: '均价', lastPrice: '现价', marketValue: '市值', unrealizedPnl: '未实现盈亏', returnPct: '收益率', action: '操作', submitting: '提交中', analyze: '分析', sectorConcentration: '行业集中度分布', positionConcentrationFallback: '行业数据暂不可用，当前展示个股集中度', noConcentrationTitle: '暂无集中度数据', noConcentrationDescription: '风险模块完成计算后，这里会展示行业或个股维度的集中度分布。', displayScope: '展示口径', sectorDimension: '行业维度', positionDimensionFallback: '个股维度（降级显示）', sectorAlert: '板块集中度告警', topWeight: 'Top1 权重', yes: '是', no: '否', writeBlocked: '当前处于“全部账户”视图。为避免误写，请先选择一个具体账户后再进行手工录入或 CSV 提交。', drawdownMonitor: '回撤监控', maxDrawdown: '最大回撤', currentDrawdown: '当前回撤', alert: '告警', stopLossWarning: '止损接近预警', triggeredCount: '触发数', nearCount: '接近数', scope: '口径', accountCount: '账户数', currency: '计价币种', costMethodShort: '成本法', aiRiskSignals: 'AI 风险信号', aiRiskUnavailable: '信号风险暂不可用', aiRiskTotal: '风险信号', sellSignals: '卖出', reduceSignals: '减仓', alertSignals: '预警', noAiRiskSignals: '暂无防御型信号' },
  en: { documentTitle: 'Portfolio Analysis - DSA', title: 'Portfolio management', description: 'Portfolio snapshots, manual entries, CSV import, and risk analysis with full-portfolio or single-account views', accountView: 'Account view', allAccounts: 'All accounts', costMethod: 'Cost method', fifo: 'FIFO', avg: 'Average cost', collapseCreate: 'Collapse', createAccount: 'New account', deleteAccount: 'Delete account', deletingAccount: 'Deleting...', deleteAccountTitle: 'Delete portfolio account', deleteAccountConfirm: 'Delete account', deleteAccountMessage: 'Delete account {name} (#{id})? It will be hidden from default lists, snapshots, risk views, and entry forms; historical ledger rows are not physically deleted.', refreshing: 'Refreshing...', refreshData: 'Refresh data', noAccounts: 'No accounts are available. Create an account before entering trades or importing CSV files.', riskDegraded: 'Risk module degraded', operationHint: 'Operation hint', analysisTask: 'Analysis task', totalEquity: 'Total equity', totalMarketValue: 'Total market value', totalCash: 'Total cash', fxStatus: 'FX status', refreshFx: 'Refresh FX', stale: 'Stale', latest: 'Current', fxRefreshResult: 'FX refresh result', positionsTitle: 'Positions', countItems: '{count} items', noPositionsTitle: 'No positions', noPositionsDescription: 'After you enter trades or import CSV data, account-level positions appear here.', account: 'Account', code: 'Code', quantity: 'Quantity', avgCost: 'Avg cost', lastPrice: 'Last price', marketValue: 'Market value', unrealizedPnl: 'Unrealized P/L', returnPct: 'Return', action: 'Action', submitting: 'Submitting', analyze: 'Analyze', sectorConcentration: 'Sector concentration', positionConcentrationFallback: 'Sector data unavailable; showing position concentration', noConcentrationTitle: 'No concentration data', noConcentrationDescription: 'Sector or position concentration appears after the risk module finishes.', displayScope: 'Display scope', sectorDimension: 'Sector', positionDimensionFallback: 'Position fallback', sectorAlert: 'Sector concentration alert', topWeight: 'Top1 weight', yes: 'Yes', no: 'No', writeBlocked: 'You are viewing all accounts. Select a specific account before manual entry or CSV submission to avoid writing to the wrong scope.', drawdownMonitor: 'Drawdown monitor', maxDrawdown: 'Max drawdown', currentDrawdown: 'Current drawdown', alert: 'Alert', stopLossWarning: 'Stop-loss proximity warning', triggeredCount: 'Triggered', nearCount: 'Near', scope: 'Scope', accountCount: 'Accounts', currency: 'Quote currency', costMethodShort: 'Cost method', aiRiskSignals: 'AI risk signals', aiRiskUnavailable: 'Signal risk unavailable', aiRiskTotal: 'Risk signals', sellSignals: 'Sell', reduceSignals: 'Reduce', alertSignals: 'Alert', noAiRiskSignals: 'No defensive signals' },
  ko: { documentTitle: '포트폴리오 분석 - DSA', title: '포트폴리오 관리', description: '전체 포트폴리오 또는 개별 계좌별 스냅샷, 수동 입력, CSV 가져오기 및 위험 분석', accountView: '계좌 보기', allAccounts: '전체 계좌', costMethod: '원가 방식', fifo: '선입선출(FIFO)', avg: '평균 단가(AVG)', collapseCreate: '접기', createAccount: '새 계좌', deleteAccount: '계좌 삭제', deletingAccount: '삭제 중...', deleteAccountTitle: '포트폴리오 계좌 삭제', deleteAccountConfirm: '계좌 삭제', deleteAccountMessage: '{name} 계좌(#{id})를 삭제할까요? 기본 목록, 스냅샷, 위험 화면과 입력 폼에서 숨겨지며 과거 원장 데이터는 물리적으로 삭제되지 않습니다.', refreshing: '새로고침 중...', refreshData: '데이터 새로고침', noAccounts: '사용 가능한 계좌가 없습니다. 거래를 입력하거나 CSV를 가져오기 전에 계좌를 만드세요.', riskDegraded: '위험 모듈 성능 저하', operationHint: '작업 안내', analysisTask: '분석 작업', totalEquity: '총 자산', totalMarketValue: '총 평가금액', totalCash: '총 현금', fxStatus: '환율 상태', refreshFx: '환율 새로고침', stale: '오래됨', latest: '최신', fxRefreshResult: '환율 새로고침 결과', positionsTitle: '보유 종목', countItems: '{count}개', noPositionsTitle: '보유 종목 없음', noPositionsDescription: '거래를 입력하거나 CSV를 가져오면 계좌별 보유 종목이 표시됩니다.', account: '계좌', code: '코드', quantity: '수량', avgCost: '평균 단가', lastPrice: '현재가', marketValue: '평가금액', unrealizedPnl: '평가손익', returnPct: '수익률', action: '작업', submitting: '제출 중', analyze: '분석', sectorConcentration: '업종 집중도', positionConcentrationFallback: '업종 데이터가 없어 종목 집중도를 표시합니다', noConcentrationTitle: '집중도 데이터 없음', noConcentrationDescription: '위험 모듈 계산 후 업종 또는 종목 집중도가 표시됩니다.', displayScope: '표시 기준', sectorDimension: '업종', positionDimensionFallback: '종목 기준(대체)', sectorAlert: '업종 집중도 경고', topWeight: '최대 종목 비중', yes: '예', no: '아니요', writeBlocked: '현재 전체 계좌를 보고 있습니다. 잘못된 계좌에 입력하지 않도록 수동 입력 또는 CSV 제출 전에 특정 계좌를 선택하세요.', drawdownMonitor: '낙폭 모니터', maxDrawdown: '최대 낙폭', currentDrawdown: '현재 낙폭', alert: '경고', stopLossWarning: '손절가 근접 경고', triggeredCount: '발동', nearCount: '근접', scope: '범위', accountCount: '계좌 수', currency: '기준 통화', costMethodShort: '원가 방식', aiRiskSignals: 'AI 위험 신호', aiRiskUnavailable: '위험 신호를 사용할 수 없음', aiRiskTotal: '위험 신호', sellSignals: '매도', reduceSignals: '비중 축소', alertSignals: '경고', noAiRiskSignals: '방어 신호 없음' },
} as const;
export const PORTFOLIO_SIDE_LABELS: Record<UiLanguage, Record<PortfolioSide, string>> = { zh: { buy: '买入', sell: '卖出' }, en: { buy: 'Buy', sell: 'Sell' }, ko: { buy: '매수', sell: '매도' } };
export const PORTFOLIO_CASH_DIRECTION_LABELS: Record<UiLanguage, Record<PortfolioCashDirection, string>> = { zh: { in: '流入', out: '流出' }, en: { in: 'Inflow', out: 'Outflow' }, ko: { in: '입금', out: '출금' } };
export const PORTFOLIO_CORPORATE_ACTION_LABELS: Record<UiLanguage, Record<PortfolioCorporateActionType, string>> = { zh: { cash_dividend: '现金分红', split_adjustment: '拆并股调整' }, en: { cash_dividend: 'Cash dividend', split_adjustment: 'Split adjustment' }, ko: { cash_dividend: '현금 배당', split_adjustment: '주식 분할/병합 조정' } };
